name: postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - pip
  - pip:
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
    - git+git://github.com/lux-org/lux-widget.git
    - git+git://github.com/lux-org/lux.git